[project]
name = "synth-demos"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "craftaxlm>=0.0.15",
    "imageio[pyav]>=2.36.0",
    "zyk==0.2.54",
]
